[colors]
[colors.primary]
background = '#1a1a1a'
foreground = '#d6d6d6'

# Normal colors
[colors.normal]
black = '#32344a'
red = '#D96164'
green = '#A7D291'
yellow = '#F5C160'
blue = '#5880B8'
magenta = '#ad8ee6'
cyan = '#449dab'
white = '#787c99'

# Bright colors
[colors.bright]
black = '#444b6a'
red = '#D96164'
green = '#A7D291'
yellow = '#F8D265'
blue = '#7da6ff'
magenta = '#bb9af7'
cyan = '#0db9d7'
white = '#acb0d0'

[colors.selection]
background = '#4d4d4d'
