[colors]
[colors.primary]
background = '#1a1a1a'
foreground = '#d6d6d6'

# Normal colors
[colors.normal]
black = '#32344a'
red = '#f7768e'
green = '#627F64'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#ad8ee6'
cyan = '#449dab'
white = '#787c99'

# Bright colors
[colors.bright]
black = '#444b6a'
red = '#ff7a93'
green = '#627f64'
yellow = '#ff9e64'
blue = '#7da6ff'
magenta = '#bb9af7'
cyan = '#0db9d7'
white = '#acb0d0'

[colors.selection]
background = '#627f64'
